# Generated by Django 5.2.16 on 2026-07-24 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customercredit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='party_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='customercredit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL),
        ),
    ]
