# Generated by Django 5.2.16 on 2026-08-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gokulam Traders', max_length=200)),
                ('address', models.CharField(default='123 Main Road, Bangalore - 560001', max_length=500)),
                ('latitude', models.FloatField(default=12.9716)),
                ('longitude', models.FloatField(default=77.5946)),
                ('delivery_radius_km', models.FloatField(default=5)),
                ('delivery_charge_per_half_km', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Configuration',
            },
        ),
    ]
